server:
  port: 8088

spring:
  kafka:
    bootstrap-servers: 10.6.120.56:9092,10.6.120.121:9092,10.6.120.67:9092
    topic: chelab-topic

    topic-setting:
      partitions: 3
      replicas: 3

logging.level:
  org:
    apache.kafka: DEBUG
