server:
  port: 8090

spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092

    topic: simple-person-topic

    topic-setting:
      partitions: 3
      replicas: 1

    consumer:
      group-id: simple-consumer-person-group


logging.level:
  org:
    apache.kafka: INFO