server:
  port: 8090

spring:
  kafka:
    bootstrap-servers: 10.6.120.56:9092,10.6.120.121:9092,10.6.120.67:9092

    topic: chelab-person-topic

    topic-setting:
      partitions: 3
      replicas: 3

    consumer:
      group-id: chelab-consumer-person-group


logging.level:
  org:
    apache.kafka: INFO